### ISSUE TITLE
Gradle Dependency Not Working 

### ISSUE THREAD

**Issue by tschiet** [ursjoss/KRis#66]
Hi,
What is the current version of this library? When I use the code from "Setup", I tried using 0.3.1 as the version number, but it did not work in the build file for Gradle: implementation("ch.difty.kris:kris-io:0.3.1") 
I get an error that the library cannot be found. 
Thanks for your help!

**Comment by ursjoss** [comment]
Hi @tschiet Yes, `0.3.1` is the latest released version of KRis. It is available on bintray. Did you include `jcenter()` as a repository?

**Comment by ursjoss** [comment]
Hi @tschiet. Is there anything I can do to support you?

**Comment by mplatt** [comment]
Hi @ursjoss,
I'm not the OP but have a similar issue. I tried with the coordinates suggested but no luck:

```
plugins {
    id 'org.jetbrains.kotlin.jvm' version '1.4.10'
}

group 'org.example'
version '1.0-SNAPSHOT'

repositories {
    jcenter()
    mavenCentral()
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib"

    implementation "ch.difty.kris:kris-core:0.3.1"
    implementation "ch.difty.kris:kris-io:0.3.1"
}
```

**Comment by ursjoss** [comment]
Hi @mplatt

Thanks for your detailed report. I'll check it out and will provide an update to this ticket today or tomorrow.

**Comment by ursjoss** [comment]
@tschiet @mplatt 

Turns out I did not actually configure my bintray repo to sync into jcenter. With the upcoming ["JCenter Sunset"](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/) I will not even attempt to do that, as I plan to publish to maven central soon anyhow.

For the time-being, please configure your repo as follows:

```
repositories {
    maven { url = uri("https://dl.bintray.com/difty/maven/") }
}
```

I will update the README accordingly.

Sorry for the hassle.

**Comment by ursjoss** [comment]
For what it's worth: KRis-0.4.0 is available in maven-central.
